version: '3'
services:
  web:
    container_name: indeleble-web
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - indeleble-network
    environment:
      - NODE_ENV=production
    restart: always

networks:
  indeleble-network:
    driver: bridge
